// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cfc.proto

package cfc_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HostIdReq struct {
	HostId               string   `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostIdReq) Reset()         { *m = HostIdReq{} }
func (m *HostIdReq) String() string { return proto.CompactTextString(m) }
func (*HostIdReq) ProtoMessage()    {}
func (*HostIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{0}
}

func (m *HostIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostIdReq.Unmarshal(m, b)
}
func (m *HostIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostIdReq.Marshal(b, m, deterministic)
}
func (m *HostIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostIdReq.Merge(m, src)
}
func (m *HostIdReq) XXX_Size() int {
	return xxx_messageInfo_HostIdReq.Size(m)
}
func (m *HostIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HostIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_HostIdReq proto.InternalMessageInfo

func (m *HostIdReq) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

type AgentInfo struct {
	HostId               string            `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Ip                   string            `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname             string            `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion         string            `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	AgentOs              string            `protobuf:"bytes,5,opt,name=agent_os,json=agentOs,proto3" json:"agent_os,omitempty"`
	AgentArch            string            `protobuf:"bytes,6,opt,name=agent_arch,json=agentArch,proto3" json:"agent_arch,omitempty"`
	Uptime               float64           `protobuf:"fixed64,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	IdlePct              float64           `protobuf:"fixed64,8,opt,name=idle_pct,json=idlePct,proto3" json:"idle_pct,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AgentInfo) Reset()         { *m = AgentInfo{} }
func (m *AgentInfo) String() string { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()    {}
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{1}
}

func (m *AgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInfo.Unmarshal(m, b)
}
func (m *AgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInfo.Marshal(b, m, deterministic)
}
func (m *AgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInfo.Merge(m, src)
}
func (m *AgentInfo) XXX_Size() int {
	return xxx_messageInfo_AgentInfo.Size(m)
}
func (m *AgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInfo proto.InternalMessageInfo

func (m *AgentInfo) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *AgentInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AgentInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AgentInfo) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *AgentInfo) GetAgentOs() string {
	if m != nil {
		return m.AgentOs
	}
	return ""
}

func (m *AgentInfo) GetAgentArch() string {
	if m != nil {
		return m.AgentArch
	}
	return ""
}

func (m *AgentInfo) GetUptime() float64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *AgentInfo) GetIdlePct() float64 {
	if m != nil {
		return m.IdlePct
	}
	return 0
}

func (m *AgentInfo) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Plugins struct {
	Plugins              []*Plugin `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Plugins) Reset()         { *m = Plugins{} }
func (m *Plugins) String() string { return proto.CompactTextString(m) }
func (*Plugins) ProtoMessage()    {}
func (*Plugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{2}
}

func (m *Plugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugins.Unmarshal(m, b)
}
func (m *Plugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugins.Marshal(b, m, deterministic)
}
func (m *Plugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugins.Merge(m, src)
}
func (m *Plugins) XXX_Size() int {
	return xxx_messageInfo_Plugins.Size(m)
}
func (m *Plugins) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugins.DiscardUnknown(m)
}

var xxx_messageInfo_Plugins proto.InternalMessageInfo

func (m *Plugins) GetPlugins() []*Plugin {
	if m != nil {
		return m.Plugins
	}
	return nil
}

type Plugin struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Checksum             string   `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Args                 string   `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	Interval             int32    `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout              int32    `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Comment              string   `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plugin) Reset()         { *m = Plugin{} }
func (m *Plugin) String() string { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()    {}
func (*Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{3}
}

func (m *Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin.Unmarshal(m, b)
}
func (m *Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin.Marshal(b, m, deterministic)
}
func (m *Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin.Merge(m, src)
}
func (m *Plugin) XXX_Size() int {
	return xxx_messageInfo_Plugin.Size(m)
}
func (m *Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin proto.InternalMessageInfo

func (m *Plugin) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Plugin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plugin) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Plugin) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *Plugin) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *Plugin) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Plugin) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Plugin) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type Metric struct {
	HostId               string            `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Metric               string            `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	DataType             string            `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Cycle                int32             `protobuf:"varint,4,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{4}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *Metric) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *Metric) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Metric) GetCycle() int32 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

func (m *Metric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*HostIdReq)(nil), "cfc_proto.HostIdReq")
	proto.RegisterType((*AgentInfo)(nil), "cfc_proto.AgentInfo")
	proto.RegisterMapType((map[string]string)(nil), "cfc_proto.AgentInfo.MetadataEntry")
	proto.RegisterType((*Plugins)(nil), "cfc_proto.Plugins")
	proto.RegisterType((*Plugin)(nil), "cfc_proto.Plugin")
	proto.RegisterType((*Metric)(nil), "cfc_proto.Metric")
	proto.RegisterMapType((map[string]string)(nil), "cfc_proto.Metric.TagsEntry")
}

func init() { proto.RegisterFile("proto/cfc.proto", fileDescriptor_102c6d1476502823) }

var fileDescriptor_102c6d1476502823 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0x26, 0x69, 0x37, 0xd9, 0x1c, 0x5d, 0x6d, 0x87, 0x5a, 0xe3, 0x16, 0xa1, 0xac, 0x5e, 0x14,
	0x84, 0x2c, 0x54, 0x50, 0xf1, 0x97, 0x22, 0x85, 0x16, 0x2c, 0x2d, 0x63, 0xf1, 0x76, 0x99, 0xce,
	0x9e, 0xcd, 0x0e, 0xcd, 0x9f, 0xc9, 0x64, 0x25, 0xef, 0xe1, 0x03, 0xf9, 0x14, 0xde, 0xfa, 0x2a,
	0x32, 0x67, 0x92, 0xb0, 0x52, 0x7b, 0xd1, 0xbb, 0xf3, 0xfd, 0xe4, 0x64, 0xe6, 0x3b, 0x67, 0xe0,
	0x61, 0x51, 0xe6, 0x3a, 0x9f, 0xca, 0x85, 0x8c, 0xa8, 0x62, 0x81, 0x5c, 0xc8, 0x19, 0x95, 0xe3,
	0xbd, 0x38, 0xcf, 0xe3, 0x04, 0xa7, 0x84, 0xae, 0xea, 0xc5, 0x14, 0xd3, 0x42, 0x37, 0xd6, 0x37,
	0x79, 0x0e, 0xc1, 0x49, 0x5e, 0xe9, 0xd3, 0x39, 0xc7, 0xef, 0xec, 0x31, 0xf8, 0xcb, 0xbc, 0xd2,
	0x33, 0x35, 0x0f, 0x9d, 0x7d, 0xe7, 0x20, 0xe0, 0xde, 0x92, 0xb4, 0xc9, 0x1f, 0x17, 0x82, 0xa3,
	0x18, 0x33, 0x7d, 0x9a, 0x2d, 0xf2, 0x5b, 0x6d, 0xec, 0x01, 0xb8, 0xaa, 0x08, 0x5d, 0xe2, 0x5c,
	0x55, 0xb0, 0x31, 0x0c, 0x8d, 0x92, 0x89, 0x14, 0xc3, 0x0d, 0x62, 0x7b, 0xcc, 0x9e, 0xc1, 0x48,
	0x98, 0x8e, 0xb3, 0x15, 0x96, 0x95, 0xca, 0xb3, 0x70, 0x93, 0x0c, 0xf7, 0x89, 0xfc, 0x66, 0x39,
	0xf6, 0x04, 0x86, 0xd6, 0x94, 0x57, 0xe1, 0x80, 0x74, 0x9f, 0xf0, 0x79, 0xc5, 0x9e, 0x02, 0x58,
	0x49, 0x94, 0x72, 0x19, 0x7a, 0x24, 0x06, 0xc4, 0x1c, 0x95, 0x72, 0xc9, 0x76, 0xc1, 0xab, 0x0b,
	0xad, 0x52, 0x0c, 0xfd, 0x7d, 0xe7, 0xc0, 0xe1, 0x2d, 0x32, 0x1d, 0xd5, 0x3c, 0xc1, 0x59, 0x21,
	0x75, 0x38, 0x24, 0xc5, 0x37, 0xf8, 0x42, 0x6a, 0xf6, 0x11, 0x86, 0x29, 0x6a, 0x31, 0x17, 0x5a,
	0x84, 0xc1, 0xfe, 0xc6, 0xc1, 0xbd, 0xc3, 0x49, 0xd4, 0xa7, 0x18, 0xf5, 0xd7, 0x8f, 0xce, 0x5a,
	0xd3, 0x71, 0xa6, 0xcb, 0x86, 0xf7, 0xdf, 0x8c, 0xdf, 0xc1, 0xe8, 0x1f, 0x89, 0x6d, 0xc1, 0xc6,
	0x35, 0x36, 0x6d, 0x46, 0xa6, 0x64, 0x3b, 0x30, 0x58, 0x89, 0xa4, 0xc6, 0x36, 0x23, 0x0b, 0xde,
	0xba, 0x6f, 0x9c, 0xc9, 0x2b, 0xf0, 0x2f, 0x92, 0x3a, 0x56, 0x59, 0xc5, 0x5e, 0x80, 0x5f, 0xd8,
	0x32, 0x74, 0xe8, 0x18, 0xdb, 0x6b, 0xc7, 0xb0, 0x26, 0xde, 0x39, 0x26, 0xbf, 0x1c, 0xf0, 0x2c,
	0x47, 0xe9, 0xdb, 0x89, 0x8c, 0xb8, 0xab, 0xe6, 0x8c, 0xc1, 0x26, 0x25, 0x6f, 0xff, 0x45, 0xb5,
	0xe1, 0x0a, 0xa1, 0x97, 0xed, 0x34, 0xa8, 0x36, 0x53, 0x92, 0x4b, 0x94, 0xd7, 0x55, 0x9d, 0xb6,
	0x43, 0xe8, 0xb1, 0xf1, 0x8b, 0x32, 0xee, 0xc2, 0xa7, 0xda, 0xf8, 0x55, 0xa6, 0xb1, 0x5c, 0x89,
	0x84, 0x72, 0x1f, 0xf0, 0x1e, 0xb3, 0x10, 0x7c, 0x13, 0x73, 0x5e, 0x6b, 0xca, 0x7d, 0xc0, 0x3b,
	0x68, 0x14, 0x99, 0xa7, 0x29, 0x66, 0x36, 0xf7, 0x80, 0x77, 0x70, 0xf2, 0xdb, 0x01, 0xef, 0x0c,
	0x75, 0xa9, 0xe4, 0xed, 0x9b, 0xb5, 0x0b, 0x5e, 0x4a, 0x96, 0xf6, 0x36, 0x2d, 0x62, 0x7b, 0x10,
	0x98, 0xbc, 0x67, 0xba, 0x29, 0xfa, 0x15, 0x33, 0xc4, 0x65, 0x53, 0xa0, 0x49, 0x5b, 0x36, 0x32,
	0x41, 0xba, 0xd5, 0x80, 0x5b, 0xc0, 0xa6, 0xb0, 0xa9, 0x05, 0x5d, 0xc9, 0x64, 0xbb, 0xb7, 0x96,
	0xad, 0x3d, 0x44, 0x74, 0x29, 0xe2, 0xca, 0xce, 0x96, 0x8c, 0xe3, 0xd7, 0x10, 0xf4, 0xd4, 0x5d,
	0x66, 0x7a, 0xf8, 0xd3, 0x85, 0xd1, 0xf9, 0x8f, 0xe4, 0xf3, 0x42, 0x7e, 0xc5, 0x72, 0xa5, 0x24,
	0xb2, 0x0f, 0x30, 0xe2, 0x18, 0xab, 0x4a, 0x63, 0x49, 0xfb, 0xc4, 0x76, 0xfe, 0xb7, 0x61, 0xe3,
	0xdd, 0xc8, 0x3e, 0xd9, 0xa8, 0x7b, 0xb2, 0xd1, 0xb1, 0x79, 0xb2, 0xec, 0x3d, 0x6c, 0x7d, 0x51,
	0x95, 0x26, 0x63, 0xb7, 0x2d, 0xeb, 0x1d, 0xfa, 0x97, 0x3c, 0x66, 0x37, 0x56, 0xa6, 0x62, 0xc7,
	0xf0, 0x88, 0xa3, 0x44, 0xb5, 0x42, 0x6a, 0x70, 0x82, 0xa2, 0xd4, 0x57, 0x28, 0xee, 0x7a, 0x88,
	0x4f, 0xc0, 0xd6, 0xdb, 0xb4, 0x93, 0xdb, 0xbe, 0x91, 0xe3, 0x6d, 0x0d, 0xae, 0x3c, 0xc2, 0x2f,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x2d, 0xcf, 0x3a, 0xb4, 0x04, 0x00, 0x00,
}
