// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cfc.proto

package cfc_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HostIdReq struct {
	HostId               string   `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostIdReq) Reset()         { *m = HostIdReq{} }
func (m *HostIdReq) String() string { return proto.CompactTextString(m) }
func (*HostIdReq) ProtoMessage()    {}
func (*HostIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{0}
}

func (m *HostIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostIdReq.Unmarshal(m, b)
}
func (m *HostIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostIdReq.Marshal(b, m, deterministic)
}
func (m *HostIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostIdReq.Merge(m, src)
}
func (m *HostIdReq) XXX_Size() int {
	return xxx_messageInfo_HostIdReq.Size(m)
}
func (m *HostIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HostIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_HostIdReq proto.InternalMessageInfo

func (m *HostIdReq) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

type PluginIdReq struct {
	PluginId             uint32   `protobuf:"varint,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginIdReq) Reset()         { *m = PluginIdReq{} }
func (m *PluginIdReq) String() string { return proto.CompactTextString(m) }
func (*PluginIdReq) ProtoMessage()    {}
func (*PluginIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{1}
}

func (m *PluginIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginIdReq.Unmarshal(m, b)
}
func (m *PluginIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginIdReq.Marshal(b, m, deterministic)
}
func (m *PluginIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginIdReq.Merge(m, src)
}
func (m *PluginIdReq) XXX_Size() int {
	return xxx_messageInfo_PluginIdReq.Size(m)
}
func (m *PluginIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_PluginIdReq proto.InternalMessageInfo

func (m *PluginIdReq) GetPluginId() uint32 {
	if m != nil {
		return m.PluginId
	}
	return 0
}

type AgentInfo struct {
	HostId               string            `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Ip                   string            `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname             string            `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion         string            `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	AgentOs              string            `protobuf:"bytes,5,opt,name=agent_os,json=agentOs,proto3" json:"agent_os,omitempty"`
	AgentArch            string            `protobuf:"bytes,6,opt,name=agent_arch,json=agentArch,proto3" json:"agent_arch,omitempty"`
	Uptime               float64           `protobuf:"fixed64,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	IdlePct              float64           `protobuf:"fixed64,8,opt,name=idle_pct,json=idlePct,proto3" json:"idle_pct,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AgentInfo) Reset()         { *m = AgentInfo{} }
func (m *AgentInfo) String() string { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()    {}
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{2}
}

func (m *AgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInfo.Unmarshal(m, b)
}
func (m *AgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInfo.Marshal(b, m, deterministic)
}
func (m *AgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInfo.Merge(m, src)
}
func (m *AgentInfo) XXX_Size() int {
	return xxx_messageInfo_AgentInfo.Size(m)
}
func (m *AgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInfo proto.InternalMessageInfo

func (m *AgentInfo) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *AgentInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AgentInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AgentInfo) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *AgentInfo) GetAgentOs() string {
	if m != nil {
		return m.AgentOs
	}
	return ""
}

func (m *AgentInfo) GetAgentArch() string {
	if m != nil {
		return m.AgentArch
	}
	return ""
}

func (m *AgentInfo) GetUptime() float64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *AgentInfo) GetIdlePct() float64 {
	if m != nil {
		return m.IdlePct
	}
	return 0
}

func (m *AgentInfo) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Plugins struct {
	Plugins              []*Plugin `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Plugins) Reset()         { *m = Plugins{} }
func (m *Plugins) String() string { return proto.CompactTextString(m) }
func (*Plugins) ProtoMessage()    {}
func (*Plugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{3}
}

func (m *Plugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugins.Unmarshal(m, b)
}
func (m *Plugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugins.Marshal(b, m, deterministic)
}
func (m *Plugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugins.Merge(m, src)
}
func (m *Plugins) XXX_Size() int {
	return xxx_messageInfo_Plugins.Size(m)
}
func (m *Plugins) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugins.DiscardUnknown(m)
}

var xxx_messageInfo_Plugins proto.InternalMessageInfo

func (m *Plugins) GetPlugins() []*Plugin {
	if m != nil {
		return m.Plugins
	}
	return nil
}

type Plugin struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Checksum             string   `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Args                 string   `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	Interval             int32    `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout              int32    `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Comment              string   `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plugin) Reset()         { *m = Plugin{} }
func (m *Plugin) String() string { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()    {}
func (*Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{4}
}

func (m *Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin.Unmarshal(m, b)
}
func (m *Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin.Marshal(b, m, deterministic)
}
func (m *Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin.Merge(m, src)
}
func (m *Plugin) XXX_Size() int {
	return xxx_messageInfo_Plugin.Size(m)
}
func (m *Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin proto.InternalMessageInfo

func (m *Plugin) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Plugin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plugin) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Plugin) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *Plugin) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *Plugin) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Plugin) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Plugin) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type Metric struct {
	HostId               string            `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Metric               string            `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	DataType             string            `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Cycle                int32             `protobuf:"varint,4,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{5}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *Metric) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *Metric) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Metric) GetCycle() int32 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

func (m *Metric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type PluginFile struct {
	Buffer               []byte   `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginFile) Reset()         { *m = PluginFile{} }
func (m *PluginFile) String() string { return proto.CompactTextString(m) }
func (*PluginFile) ProtoMessage()    {}
func (*PluginFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_102c6d1476502823, []int{6}
}

func (m *PluginFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginFile.Unmarshal(m, b)
}
func (m *PluginFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginFile.Marshal(b, m, deterministic)
}
func (m *PluginFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginFile.Merge(m, src)
}
func (m *PluginFile) XXX_Size() int {
	return xxx_messageInfo_PluginFile.Size(m)
}
func (m *PluginFile) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginFile.DiscardUnknown(m)
}

var xxx_messageInfo_PluginFile proto.InternalMessageInfo

func (m *PluginFile) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func init() {
	proto.RegisterType((*HostIdReq)(nil), "cfc_proto.HostIdReq")
	proto.RegisterType((*PluginIdReq)(nil), "cfc_proto.PluginIdReq")
	proto.RegisterType((*AgentInfo)(nil), "cfc_proto.AgentInfo")
	proto.RegisterMapType((map[string]string)(nil), "cfc_proto.AgentInfo.MetadataEntry")
	proto.RegisterType((*Plugins)(nil), "cfc_proto.Plugins")
	proto.RegisterType((*Plugin)(nil), "cfc_proto.Plugin")
	proto.RegisterType((*Metric)(nil), "cfc_proto.Metric")
	proto.RegisterMapType((map[string]string)(nil), "cfc_proto.Metric.TagsEntry")
	proto.RegisterType((*PluginFile)(nil), "cfc_proto.PluginFile")
}

func init() { proto.RegisterFile("proto/cfc.proto", fileDescriptor_102c6d1476502823) }

var fileDescriptor_102c6d1476502823 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x6b, 0xdb, 0x4a,
	0x10, 0x45, 0x4e, 0x6c, 0x59, 0x93, 0xf8, 0xde, 0x64, 0x49, 0x72, 0x75, 0x1d, 0x2e, 0x04, 0xdd,
	0x3c, 0x84, 0x16, 0xe4, 0x92, 0x42, 0x5b, 0xfa, 0x49, 0x68, 0x5d, 0x12, 0x68, 0x48, 0x50, 0x43,
	0x5f, 0xcd, 0x7a, 0x3d, 0x92, 0x97, 0xe8, 0xab, 0xd2, 0xca, 0xc1, 0xff, 0xae, 0xbf, 0xa2, 0x2f,
	0x7d, 0xe8, 0x5f, 0x29, 0x3b, 0x2b, 0x09, 0x17, 0x37, 0x0f, 0x79, 0x9b, 0x73, 0xe6, 0x68, 0x34,
	0x73, 0x66, 0x58, 0xf8, 0x3b, 0x2f, 0x32, 0x95, 0x8d, 0x44, 0x28, 0x7c, 0x8a, 0x98, 0x23, 0x42,
	0x31, 0xa1, 0x70, 0x78, 0x18, 0x65, 0x59, 0x14, 0xe3, 0x88, 0xd0, 0xb4, 0x0a, 0x47, 0x98, 0xe4,
	0x6a, 0x69, 0x74, 0xde, 0x31, 0x38, 0xe7, 0x59, 0xa9, 0x2e, 0x66, 0x01, 0x7e, 0x65, 0xff, 0x80,
	0x3d, 0xcf, 0x4a, 0x35, 0x91, 0x33, 0xd7, 0x3a, 0xb2, 0x4e, 0x9c, 0xa0, 0x37, 0xa7, 0x9c, 0xf7,
	0x08, 0xb6, 0xae, 0xe3, 0x2a, 0x92, 0xa9, 0xd1, 0x1d, 0x82, 0x93, 0x13, 0x6c, 0x94, 0x83, 0xa0,
	0x9f, 0xd7, 0x79, 0xef, 0x67, 0x07, 0x9c, 0xb3, 0x08, 0x53, 0x75, 0x91, 0x86, 0xd9, 0xbd, 0x25,
	0xd9, 0x5f, 0xd0, 0x91, 0xb9, 0xdb, 0x21, 0xae, 0x23, 0x73, 0x36, 0x84, 0xbe, 0xce, 0xa4, 0x3c,
	0x41, 0x77, 0x83, 0xd8, 0x16, 0xb3, 0xff, 0x61, 0xc0, 0x75, 0xc5, 0xc9, 0x02, 0x8b, 0x52, 0x66,
	0xa9, 0xbb, 0x49, 0x82, 0x6d, 0x22, 0xbf, 0x18, 0x8e, 0xfd, 0x0b, 0x7d, 0x23, 0xca, 0x4a, 0xb7,
	0x4b, 0x79, 0x9b, 0xf0, 0x55, 0xc9, 0xfe, 0x03, 0x30, 0x29, 0x5e, 0x88, 0xb9, 0xdb, 0xa3, 0xa4,
	0x43, 0xcc, 0x59, 0x21, 0xe6, 0xec, 0x00, 0x7a, 0x55, 0xae, 0x64, 0x82, 0xae, 0x7d, 0x64, 0x9d,
	0x58, 0x41, 0x8d, 0x74, 0x45, 0x39, 0x8b, 0x71, 0x92, 0x0b, 0xe5, 0xf6, 0x29, 0x63, 0x6b, 0x7c,
	0x2d, 0x14, 0x7b, 0x0b, 0xfd, 0x04, 0x15, 0x9f, 0x71, 0xc5, 0x5d, 0xe7, 0x68, 0xe3, 0x64, 0xeb,
	0xd4, 0xf3, 0x5b, 0xc7, 0xfd, 0x76, 0x7c, 0xff, 0xb2, 0x16, 0x8d, 0x53, 0x55, 0x2c, 0x83, 0xf6,
	0x9b, 0xe1, 0x2b, 0x18, 0xfc, 0x96, 0x62, 0x3b, 0xb0, 0x71, 0x8b, 0xcb, 0xda, 0x23, 0x1d, 0xb2,
	0x3d, 0xe8, 0x2e, 0x78, 0x5c, 0x61, 0xed, 0x91, 0x01, 0x2f, 0x3b, 0x2f, 0x2c, 0xef, 0x19, 0xd8,
	0x66, 0x1b, 0x25, 0x7b, 0x0c, 0xb6, 0x31, 0xbe, 0x74, 0x2d, 0x6a, 0x63, 0x77, 0xa5, 0x0d, 0x23,
	0x0a, 0x1a, 0x85, 0xf7, 0xcd, 0x82, 0x9e, 0xe1, 0xc8, 0xfd, 0x66, 0x75, 0x1d, 0x39, 0x63, 0x0c,
	0x36, 0xc9, 0x79, 0xf3, 0x2f, 0x8a, 0x35, 0x97, 0x73, 0x35, 0xaf, 0xb7, 0x41, 0xb1, 0xde, 0x92,
	0x98, 0xa3, 0xb8, 0x2d, 0xab, 0xa4, 0x5e, 0x42, 0x8b, 0xb5, 0x9e, 0x17, 0x51, 0x63, 0x3e, 0xc5,
	0x5a, 0x2f, 0x53, 0x85, 0xc5, 0x82, 0xc7, 0xe4, 0x7b, 0x37, 0x68, 0x31, 0x73, 0xc1, 0xd6, 0x36,
	0x67, 0x95, 0x22, 0xdf, 0xbb, 0x41, 0x03, 0x75, 0x46, 0x64, 0x49, 0x82, 0xa9, 0xf1, 0xdd, 0x09,
	0x1a, 0xe8, 0x7d, 0xb7, 0xa0, 0x77, 0x89, 0xaa, 0x90, 0xe2, 0xfe, 0xcb, 0x3a, 0x80, 0x5e, 0x42,
	0x92, 0x7a, 0x9a, 0x1a, 0xe9, 0xab, 0xd5, 0x7e, 0x4f, 0xd4, 0x32, 0x6f, 0x4f, 0x4c, 0x13, 0x37,
	0xcb, 0x1c, 0xb5, 0xdb, 0x62, 0x29, 0x62, 0xa4, 0xa9, 0xba, 0x81, 0x01, 0x6c, 0x04, 0x9b, 0x8a,
	0xd3, 0x48, 0xda, 0xdb, 0xc3, 0x15, 0x6f, 0x4d, 0x13, 0xfe, 0x0d, 0x8f, 0x4a, 0xb3, 0x5b, 0x12,
	0x0e, 0x9f, 0x83, 0xd3, 0x52, 0x0f, 0xda, 0xe9, 0x31, 0x80, 0x59, 0xcd, 0x47, 0x19, 0xa3, 0x1e,
	0x61, 0x5a, 0x85, 0x21, 0x16, 0xf4, 0xf1, 0x76, 0x50, 0xa3, 0xd3, 0x1f, 0x1d, 0x18, 0x5c, 0xdd,
	0xc5, 0xef, 0x43, 0xf1, 0x19, 0x8b, 0x85, 0x14, 0xc8, 0xde, 0xc0, 0x20, 0xc0, 0x48, 0x96, 0x0a,
	0x0b, 0xba, 0x3a, 0xb6, 0xf7, 0xa7, 0x3b, 0x1c, 0x1e, 0xf8, 0xe6, 0x11, 0xf0, 0x9b, 0x47, 0xc0,
	0x1f, 0xeb, 0x47, 0x80, 0xbd, 0x86, 0x9d, 0x4f, 0xb2, 0x54, 0x24, 0x6c, 0x6e, 0x6a, 0xb5, 0x42,
	0xfb, 0x36, 0x0c, 0xd9, 0xda, 0x61, 0x95, 0x6c, 0x0c, 0xec, 0x43, 0x76, 0x97, 0xc6, 0x19, 0x9f,
	0xad, 0x36, 0xbf, 0xa6, 0x34, 0x15, 0xf6, 0xd7, 0x78, 0x2d, 0x7f, 0x62, 0xb1, 0x31, 0xec, 0x07,
	0x28, 0x50, 0x2e, 0x90, 0xfa, 0x38, 0x47, 0x5e, 0xa8, 0x29, 0xf2, 0x87, 0xce, 0xf2, 0x0e, 0xd8,
	0x6a, 0x99, 0xfa, 0x4c, 0x76, 0xd7, 0x96, 0x76, 0x5f, 0x81, 0x69, 0x8f, 0xf0, 0xd3, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x83, 0x9e, 0xd9, 0x20, 0x4d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OwlCfcServiceClient is the client API for OwlCfcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OwlCfcServiceClient interface {
	// RegisterAgent 客户端注册
	RegisterAgent(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListAgentPlugins 列出客户端需要执行的插件
	ListAgentPlugins(ctx context.Context, in *HostIdReq, opts ...grpc.CallOption) (*Plugins, error)
	// DownloadPluginFile 下载插件文件
	DownloadPluginFile(ctx context.Context, in *PluginIdReq, opts ...grpc.CallOption) (OwlCfcService_DownloadPluginFileClient, error)
	// ReceiveAgentHeartbeat 接收客户端上报的心跳
	ReceiveAgentHeartbeat(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ReceiveAgentMetric 接收客户端上报的Metric
	ReceiveAgentMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type owlCfcServiceClient struct {
	cc *grpc.ClientConn
}

func NewOwlCfcServiceClient(cc *grpc.ClientConn) OwlCfcServiceClient {
	return &owlCfcServiceClient{cc}
}

func (c *owlCfcServiceClient) RegisterAgent(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/cfc_proto.OwlCfcService/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlCfcServiceClient) ListAgentPlugins(ctx context.Context, in *HostIdReq, opts ...grpc.CallOption) (*Plugins, error) {
	out := new(Plugins)
	err := c.cc.Invoke(ctx, "/cfc_proto.OwlCfcService/ListAgentPlugins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlCfcServiceClient) DownloadPluginFile(ctx context.Context, in *PluginIdReq, opts ...grpc.CallOption) (OwlCfcService_DownloadPluginFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OwlCfcService_serviceDesc.Streams[0], "/cfc_proto.OwlCfcService/DownloadPluginFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &owlCfcServiceDownloadPluginFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OwlCfcService_DownloadPluginFileClient interface {
	Recv() (*PluginFile, error)
	grpc.ClientStream
}

type owlCfcServiceDownloadPluginFileClient struct {
	grpc.ClientStream
}

func (x *owlCfcServiceDownloadPluginFileClient) Recv() (*PluginFile, error) {
	m := new(PluginFile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *owlCfcServiceClient) ReceiveAgentHeartbeat(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/cfc_proto.OwlCfcService/ReceiveAgentHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlCfcServiceClient) ReceiveAgentMetric(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/cfc_proto.OwlCfcService/ReceiveAgentMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OwlCfcServiceServer is the server API for OwlCfcService service.
type OwlCfcServiceServer interface {
	// RegisterAgent 客户端注册
	RegisterAgent(context.Context, *AgentInfo) (*emptypb.Empty, error)
	// ListAgentPlugins 列出客户端需要执行的插件
	ListAgentPlugins(context.Context, *HostIdReq) (*Plugins, error)
	// DownloadPluginFile 下载插件文件
	DownloadPluginFile(*PluginIdReq, OwlCfcService_DownloadPluginFileServer) error
	// ReceiveAgentHeartbeat 接收客户端上报的心跳
	ReceiveAgentHeartbeat(context.Context, *AgentInfo) (*emptypb.Empty, error)
	// ReceiveAgentMetric 接收客户端上报的Metric
	ReceiveAgentMetric(context.Context, *Metric) (*emptypb.Empty, error)
}

func RegisterOwlCfcServiceServer(s *grpc.Server, srv OwlCfcServiceServer) {
	s.RegisterService(&_OwlCfcService_serviceDesc, srv)
}

func _OwlCfcService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlCfcServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cfc_proto.OwlCfcService/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlCfcServiceServer).RegisterAgent(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwlCfcService_ListAgentPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlCfcServiceServer).ListAgentPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cfc_proto.OwlCfcService/ListAgentPlugins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlCfcServiceServer).ListAgentPlugins(ctx, req.(*HostIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwlCfcService_DownloadPluginFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PluginIdReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OwlCfcServiceServer).DownloadPluginFile(m, &owlCfcServiceDownloadPluginFileServer{stream})
}

type OwlCfcService_DownloadPluginFileServer interface {
	Send(*PluginFile) error
	grpc.ServerStream
}

type owlCfcServiceDownloadPluginFileServer struct {
	grpc.ServerStream
}

func (x *owlCfcServiceDownloadPluginFileServer) Send(m *PluginFile) error {
	return x.ServerStream.SendMsg(m)
}

func _OwlCfcService_ReceiveAgentHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlCfcServiceServer).ReceiveAgentHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cfc_proto.OwlCfcService/ReceiveAgentHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlCfcServiceServer).ReceiveAgentHeartbeat(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwlCfcService_ReceiveAgentMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlCfcServiceServer).ReceiveAgentMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cfc_proto.OwlCfcService/ReceiveAgentMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlCfcServiceServer).ReceiveAgentMetric(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

var _OwlCfcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cfc_proto.OwlCfcService",
	HandlerType: (*OwlCfcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _OwlCfcService_RegisterAgent_Handler,
		},
		{
			MethodName: "ListAgentPlugins",
			Handler:    _OwlCfcService_ListAgentPlugins_Handler,
		},
		{
			MethodName: "ReceiveAgentHeartbeat",
			Handler:    _OwlCfcService_ReceiveAgentHeartbeat_Handler,
		},
		{
			MethodName: "ReceiveAgentMetric",
			Handler:    _OwlCfcService_ReceiveAgentMetric_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadPluginFile",
			Handler:       _OwlCfcService_DownloadPluginFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/cfc.proto",
}
