// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package proxypb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
	proto1 "owl/common/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DownloadPluginReq struct {
	RelPath              string   `protobuf:"bytes,1,opt,name=rel_path,json=relPath,proto3" json:"rel_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadPluginReq) Reset()         { *m = DownloadPluginReq{} }
func (m *DownloadPluginReq) String() string { return proto.CompactTextString(m) }
func (*DownloadPluginReq) ProtoMessage()    {}
func (*DownloadPluginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *DownloadPluginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadPluginReq.Unmarshal(m, b)
}
func (m *DownloadPluginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadPluginReq.Marshal(b, m, deterministic)
}
func (m *DownloadPluginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadPluginReq.Merge(m, src)
}
func (m *DownloadPluginReq) XXX_Size() int {
	return xxx_messageInfo_DownloadPluginReq.Size(m)
}
func (m *DownloadPluginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadPluginReq.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadPluginReq proto.InternalMessageInfo

func (m *DownloadPluginReq) GetRelPath() string {
	if m != nil {
		return m.RelPath
	}
	return ""
}

type PluginFile struct {
	Buffer               []byte   `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginFile) Reset()         { *m = PluginFile{} }
func (m *PluginFile) String() string { return proto.CompactTextString(m) }
func (*PluginFile) ProtoMessage()    {}
func (*PluginFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *PluginFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginFile.Unmarshal(m, b)
}
func (m *PluginFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginFile.Marshal(b, m, deterministic)
}
func (m *PluginFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginFile.Merge(m, src)
}
func (m *PluginFile) XXX_Size() int {
	return xxx_messageInfo_PluginFile.Size(m)
}
func (m *PluginFile) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginFile.DiscardUnknown(m)
}

var xxx_messageInfo_PluginFile proto.InternalMessageInfo

func (m *PluginFile) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func init() {
	proto.RegisterType((*DownloadPluginReq)(nil), "owl.proxy.DownloadPluginReq")
	proto.RegisterType((*PluginFile)(nil), "owl.proxy.PluginFile")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4f, 0xea, 0x40,
	0x14, 0x85, 0x43, 0xf2, 0x02, 0x8f, 0xfb, 0x9e, 0x51, 0x87, 0x80, 0x52, 0x5d, 0x18, 0xe2, 0xc2,
	0xd5, 0x60, 0x74, 0x4f, 0x04, 0x91, 0x40, 0x94, 0x48, 0x0a, 0x2b, 0x37, 0x66, 0x5a, 0x6e, 0xcb,
	0x24, 0xd3, 0x4e, 0x99, 0x0e, 0x20, 0xff, 0xce, 0x9f, 0x66, 0x98, 0x02, 0xd2, 0xd4, 0x2e, 0x5c,
	0xce, 0x3d, 0xa7, 0x5f, 0xce, 0x49, 0x0f, 0xfc, 0x8b, 0x94, 0xfc, 0x58, 0xd3, 0x48, 0x49, 0x2d,
	0x49, 0x59, 0xae, 0x04, 0x35, 0x07, 0xeb, 0xc2, 0x97, 0xd2, 0x17, 0xd8, 0x34, 0x82, 0xb3, 0xf0,
	0x9a, 0x18, 0x44, 0x7a, 0xeb, 0xb3, 0xea, 0xae, 0x0c, 0x02, 0x19, 0x26, 0x62, 0x33, 0x79, 0x24,
	0x52, 0x83, 0xc2, 0x69, 0x57, 0xae, 0x42, 0x21, 0xd9, 0x74, 0x24, 0x16, 0x3e, 0x0f, 0x6d, 0x9c,
	0x93, 0x3a, 0xfc, 0x55, 0x28, 0xde, 0x23, 0xa6, 0x67, 0xe7, 0x85, 0xab, 0xc2, 0x4d, 0xd9, 0x2e,
	0x29, 0x14, 0x23, 0xa6, 0x67, 0x8d, 0x6b, 0x80, 0xc4, 0xd7, 0xe3, 0x02, 0x49, 0x0d, 0x8a, 0xce,
	0xc2, 0xf3, 0x50, 0x19, 0xdb, 0x7f, 0x7b, 0xfb, 0xba, 0xfb, 0xfc, 0x03, 0xc7, 0xaf, 0x2b, 0x31,
	0xda, 0x44, 0x1b, 0xa3, 0x5a, 0x72, 0x17, 0xc9, 0x23, 0x54, 0x6d, 0x74, 0x91, 0x2f, 0x71, 0xc2,
	0x03, 0x1c, 0xa3, 0xe2, 0x18, 0x77, 0x99, 0x66, 0x84, 0xd0, 0x4d, 0x8d, 0x6d, 0xaa, 0x89, 0xb9,
	0x59, 0x35, 0x9a, 0xf4, 0xa1, 0xbb, 0x3e, 0xf4, 0x69, 0xd3, 0x87, 0x0c, 0xc1, 0xfa, 0x11, 0xd2,
	0x56, 0x8a, 0xad, 0xc9, 0x59, 0x96, 0x64, 0x84, 0x5c, 0x5c, 0x6f, 0x9f, 0xa9, 0xed, 0x63, 0xa8,
	0xfb, 0xc8, 0x94, 0x76, 0x90, 0x69, 0x52, 0x3d, 0x24, 0x19, 0x6d, 0x10, 0x7a, 0x32, 0x97, 0xf3,
	0x00, 0xe4, 0x90, 0x33, 0x44, 0xad, 0xb8, 0x9b, 0x2e, 0x96, 0xdc, 0x72, 0x09, 0x1d, 0xa8, 0x64,
	0x09, 0x31, 0xa9, 0x64, 0x11, 0x71, 0x2e, 0xa3, 0x05, 0x47, 0x36, 0xfa, 0x3c, 0xd6, 0xa8, 0x0c,
	0xe4, 0xb7, 0x2d, 0x5a, 0x70, 0xf2, 0xc2, 0x63, 0x6d, 0x8c, 0xc9, 0x4f, 0x8e, 0xd3, 0x88, 0xbe,
	0x8c, 0xf5, 0x60, 0x6a, 0xe3, 0xdc, 0x4a, 0xe5, 0xda, 0x79, 0x9f, 0x81, 0xa4, 0xb7, 0x64, 0x36,
	0x72, 0x49, 0xf7, 0x2b, 0xa5, 0x99, 0xa9, 0x59, 0xd5, 0x03, 0xf5, 0xfb, 0xa3, 0xdb, 0x42, 0xa7,
	0xfc, 0x56, 0x32, 0xd7, 0xc8, 0x71, 0x8a, 0x26, 0xe7, 0xfd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x11, 0x32, 0xcf, 0x2a, 0xfc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OwlProxyServiceClient is the client API for OwlProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OwlProxyServiceClient interface {
	// ReceiveTimeSeriesData 中继器接收数据
	ReceiveTimeSeriesData(ctx context.Context, in *proto1.TsData, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ReceiveTimeSeriesDataArray 中继器批量接收数据
	ReceiveTimeSeriesDataArray(ctx context.Context, in *proto1.TsDataArray, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ReceiveAgentHeartbeat 接收客户端上报的心跳
	ReceiveAgentHeartbeat(ctx context.Context, in *proto1.AgentInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ReceiveAgentMetric 接收客户端上报的Metric
	ReceiveAgentMetric(ctx context.Context, in *proto1.Metric, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ReceiveAgentMetrics 接收客户端上报的批量Metric
	ReceiveAgentMetrics(ctx context.Context, in *proto1.Metrics, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RegisterAgent 客户端注册
	RegisterAgent(ctx context.Context, in *proto1.AgentInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListAgentPlugins 列出客户端需要执行的插件
	ListAgentPlugins(ctx context.Context, in *proto1.HostIdReq, opts ...grpc.CallOption) (*proto1.Plugins, error)
	// DownloadPluginFile 下载插件文件
	DownloadPluginFile(ctx context.Context, in *DownloadPluginReq, opts ...grpc.CallOption) (OwlProxyService_DownloadPluginFileClient, error)
}

type owlProxyServiceClient struct {
	cc *grpc.ClientConn
}

func NewOwlProxyServiceClient(cc *grpc.ClientConn) OwlProxyServiceClient {
	return &owlProxyServiceClient{cc}
}

func (c *owlProxyServiceClient) ReceiveTimeSeriesData(ctx context.Context, in *proto1.TsData, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/owl.proxy.OwlProxyService/ReceiveTimeSeriesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlProxyServiceClient) ReceiveTimeSeriesDataArray(ctx context.Context, in *proto1.TsDataArray, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/owl.proxy.OwlProxyService/ReceiveTimeSeriesDataArray", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlProxyServiceClient) ReceiveAgentHeartbeat(ctx context.Context, in *proto1.AgentInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/owl.proxy.OwlProxyService/ReceiveAgentHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlProxyServiceClient) ReceiveAgentMetric(ctx context.Context, in *proto1.Metric, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/owl.proxy.OwlProxyService/ReceiveAgentMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlProxyServiceClient) ReceiveAgentMetrics(ctx context.Context, in *proto1.Metrics, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/owl.proxy.OwlProxyService/ReceiveAgentMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlProxyServiceClient) RegisterAgent(ctx context.Context, in *proto1.AgentInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/owl.proxy.OwlProxyService/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlProxyServiceClient) ListAgentPlugins(ctx context.Context, in *proto1.HostIdReq, opts ...grpc.CallOption) (*proto1.Plugins, error) {
	out := new(proto1.Plugins)
	err := c.cc.Invoke(ctx, "/owl.proxy.OwlProxyService/ListAgentPlugins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlProxyServiceClient) DownloadPluginFile(ctx context.Context, in *DownloadPluginReq, opts ...grpc.CallOption) (OwlProxyService_DownloadPluginFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OwlProxyService_serviceDesc.Streams[0], "/owl.proxy.OwlProxyService/DownloadPluginFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &owlProxyServiceDownloadPluginFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OwlProxyService_DownloadPluginFileClient interface {
	Recv() (*PluginFile, error)
	grpc.ClientStream
}

type owlProxyServiceDownloadPluginFileClient struct {
	grpc.ClientStream
}

func (x *owlProxyServiceDownloadPluginFileClient) Recv() (*PluginFile, error) {
	m := new(PluginFile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OwlProxyServiceServer is the server API for OwlProxyService service.
type OwlProxyServiceServer interface {
	// ReceiveTimeSeriesData 中继器接收数据
	ReceiveTimeSeriesData(context.Context, *proto1.TsData) (*emptypb.Empty, error)
	// ReceiveTimeSeriesDataArray 中继器批量接收数据
	ReceiveTimeSeriesDataArray(context.Context, *proto1.TsDataArray) (*emptypb.Empty, error)
	// ReceiveAgentHeartbeat 接收客户端上报的心跳
	ReceiveAgentHeartbeat(context.Context, *proto1.AgentInfo) (*emptypb.Empty, error)
	// ReceiveAgentMetric 接收客户端上报的Metric
	ReceiveAgentMetric(context.Context, *proto1.Metric) (*emptypb.Empty, error)
	// ReceiveAgentMetrics 接收客户端上报的批量Metric
	ReceiveAgentMetrics(context.Context, *proto1.Metrics) (*emptypb.Empty, error)
	// RegisterAgent 客户端注册
	RegisterAgent(context.Context, *proto1.AgentInfo) (*emptypb.Empty, error)
	// ListAgentPlugins 列出客户端需要执行的插件
	ListAgentPlugins(context.Context, *proto1.HostIdReq) (*proto1.Plugins, error)
	// DownloadPluginFile 下载插件文件
	DownloadPluginFile(*DownloadPluginReq, OwlProxyService_DownloadPluginFileServer) error
}

func RegisterOwlProxyServiceServer(s *grpc.Server, srv OwlProxyServiceServer) {
	s.RegisterService(&_OwlProxyService_serviceDesc, srv)
}

func _OwlProxyService_ReceiveTimeSeriesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.TsData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlProxyServiceServer).ReceiveTimeSeriesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/owl.proxy.OwlProxyService/ReceiveTimeSeriesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlProxyServiceServer).ReceiveTimeSeriesData(ctx, req.(*proto1.TsData))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwlProxyService_ReceiveTimeSeriesDataArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.TsDataArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlProxyServiceServer).ReceiveTimeSeriesDataArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/owl.proxy.OwlProxyService/ReceiveTimeSeriesDataArray",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlProxyServiceServer).ReceiveTimeSeriesDataArray(ctx, req.(*proto1.TsDataArray))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwlProxyService_ReceiveAgentHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlProxyServiceServer).ReceiveAgentHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/owl.proxy.OwlProxyService/ReceiveAgentHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlProxyServiceServer).ReceiveAgentHeartbeat(ctx, req.(*proto1.AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwlProxyService_ReceiveAgentMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlProxyServiceServer).ReceiveAgentMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/owl.proxy.OwlProxyService/ReceiveAgentMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlProxyServiceServer).ReceiveAgentMetric(ctx, req.(*proto1.Metric))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwlProxyService_ReceiveAgentMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.Metrics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlProxyServiceServer).ReceiveAgentMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/owl.proxy.OwlProxyService/ReceiveAgentMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlProxyServiceServer).ReceiveAgentMetrics(ctx, req.(*proto1.Metrics))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwlProxyService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlProxyServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/owl.proxy.OwlProxyService/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlProxyServiceServer).RegisterAgent(ctx, req.(*proto1.AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwlProxyService_ListAgentPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.HostIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlProxyServiceServer).ListAgentPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/owl.proxy.OwlProxyService/ListAgentPlugins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlProxyServiceServer).ListAgentPlugins(ctx, req.(*proto1.HostIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwlProxyService_DownloadPluginFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadPluginReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OwlProxyServiceServer).DownloadPluginFile(m, &owlProxyServiceDownloadPluginFileServer{stream})
}

type OwlProxyService_DownloadPluginFileServer interface {
	Send(*PluginFile) error
	grpc.ServerStream
}

type owlProxyServiceDownloadPluginFileServer struct {
	grpc.ServerStream
}

func (x *owlProxyServiceDownloadPluginFileServer) Send(m *PluginFile) error {
	return x.ServerStream.SendMsg(m)
}

var _OwlProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "owl.proxy.OwlProxyService",
	HandlerType: (*OwlProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveTimeSeriesData",
			Handler:    _OwlProxyService_ReceiveTimeSeriesData_Handler,
		},
		{
			MethodName: "ReceiveTimeSeriesDataArray",
			Handler:    _OwlProxyService_ReceiveTimeSeriesDataArray_Handler,
		},
		{
			MethodName: "ReceiveAgentHeartbeat",
			Handler:    _OwlProxyService_ReceiveAgentHeartbeat_Handler,
		},
		{
			MethodName: "ReceiveAgentMetric",
			Handler:    _OwlProxyService_ReceiveAgentMetric_Handler,
		},
		{
			MethodName: "ReceiveAgentMetrics",
			Handler:    _OwlProxyService_ReceiveAgentMetrics_Handler,
		},
		{
			MethodName: "RegisterAgent",
			Handler:    _OwlProxyService_RegisterAgent_Handler,
		},
		{
			MethodName: "ListAgentPlugins",
			Handler:    _OwlProxyService_ListAgentPlugins_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadPluginFile",
			Handler:       _OwlProxyService_DownloadPluginFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proxy.proto",
}
