// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/repeater.proto

package repeater_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TsData struct {
	Metric               string            `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	DataType             string            `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Value                float64           `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp            int64             `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Cycle                int32             `protobuf:"varint,5,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TsData) Reset()         { *m = TsData{} }
func (m *TsData) String() string { return proto.CompactTextString(m) }
func (*TsData) ProtoMessage()    {}
func (*TsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c615aef7eb5a6f3a, []int{0}
}

func (m *TsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TsData.Unmarshal(m, b)
}
func (m *TsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TsData.Marshal(b, m, deterministic)
}
func (m *TsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TsData.Merge(m, src)
}
func (m *TsData) XXX_Size() int {
	return xxx_messageInfo_TsData.Size(m)
}
func (m *TsData) XXX_DiscardUnknown() {
	xxx_messageInfo_TsData.DiscardUnknown(m)
}

var xxx_messageInfo_TsData proto.InternalMessageInfo

func (m *TsData) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *TsData) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *TsData) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TsData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TsData) GetCycle() int32 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

func (m *TsData) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*TsData)(nil), "repeater_proto.TsData")
	proto.RegisterMapType((map[string]string)(nil), "repeater_proto.TsData.TagsEntry")
}

func init() { proto.RegisterFile("proto/repeater.proto", fileDescriptor_c615aef7eb5a6f3a) }

var fileDescriptor_c615aef7eb5a6f3a = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xc9, 0xba, 0x16, 0x1b, 0x41, 0x24, 0xcc, 0x11, 0x3a, 0x0f, 0xc1, 0x53, 0x4f, 0x29,
	0x4c, 0x41, 0xf1, 0xec, 0xf0, 0x28, 0x64, 0xbd, 0xca, 0xc8, 0xea, 0xb3, 0x04, 0x5b, 0x1b, 0xd2,
	0xac, 0x92, 0x7f, 0xdc, 0xb3, 0x34, 0xe9, 0x1c, 0x82, 0xb7, 0xfc, 0xbe, 0xbc, 0x90, 0xdf, 0xfb,
	0xf0, 0x42, 0x9b, 0xce, 0x76, 0x85, 0x01, 0x0d, 0xd2, 0x82, 0xe1, 0x1e, 0xc9, 0xc5, 0x91, 0x77,
	0x9e, 0xb3, 0x55, 0xdd, 0x75, 0x75, 0x03, 0x85, 0xa7, 0xfd, 0xe1, 0xbd, 0x80, 0x56, 0x5b, 0x17,
	0x86, 0x6f, 0xbe, 0x11, 0x4e, 0xca, 0xfe, 0x49, 0x5a, 0x49, 0x96, 0x38, 0x69, 0xc1, 0x1a, 0x55,
	0x51, 0xc4, 0x50, 0x9e, 0x8a, 0x89, 0xc8, 0x0a, 0xa7, 0x6f, 0xd2, 0xca, 0x9d, 0x75, 0x1a, 0xe8,
	0xcc, 0x5f, 0x9d, 0x8d, 0x41, 0xe9, 0x34, 0x90, 0x05, 0x8e, 0x07, 0xd9, 0x1c, 0x80, 0x46, 0x0c,
	0xe5, 0x48, 0x04, 0x20, 0xd7, 0x38, 0xb5, 0xaa, 0x85, 0xde, 0xca, 0x56, 0xd3, 0x39, 0x43, 0x79,
	0x24, 0x4e, 0xc1, 0xf8, 0xa6, 0x72, 0x55, 0x03, 0x34, 0x66, 0x28, 0x8f, 0x45, 0x00, 0x72, 0x87,
	0xe7, 0x56, 0xd6, 0x3d, 0x4d, 0x58, 0x94, 0x9f, 0xaf, 0x19, 0xff, 0xbb, 0x05, 0x0f, 0x92, 0xbc,
	0x94, 0x75, 0xbf, 0xf9, 0xb4, 0xc6, 0x09, 0x3f, 0x9d, 0xdd, 0xe3, 0xf4, 0x37, 0x22, 0x97, 0x38,
	0xfa, 0x00, 0x37, 0xe9, 0x8f, 0xc7, 0x93, 0x5e, 0xf0, 0x0e, 0xf0, 0x38, 0x7b, 0x40, 0xeb, 0x57,
	0x4c, 0x5e, 0xbe, 0x1a, 0x31, 0x7d, 0xb2, 0x05, 0x33, 0xa8, 0x0a, 0xc8, 0x33, 0xbe, 0x12, 0x50,
	0x81, 0x1a, 0xa0, 0x54, 0x2d, 0x6c, 0xc1, 0x28, 0x98, 0xca, 0xf9, 0xdf, 0x27, 0x5b, 0xf2, 0xd0,
	0x2e, 0x3f, 0xb6, 0xcb, 0x37, 0x63, 0xbb, 0xfb, 0xc4, 0xf3, 0xed, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8f, 0x82, 0x32, 0x64, 0xa3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OwlRepeaterServiceClient is the client API for OwlRepeaterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OwlRepeaterServiceClient interface {
	// ReceiveTimeSeriesData 中继器接收数据
	ReceiveTimeSeriesData(ctx context.Context, in *TsData, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type owlRepeaterServiceClient struct {
	cc *grpc.ClientConn
}

func NewOwlRepeaterServiceClient(cc *grpc.ClientConn) OwlRepeaterServiceClient {
	return &owlRepeaterServiceClient{cc}
}

func (c *owlRepeaterServiceClient) ReceiveTimeSeriesData(ctx context.Context, in *TsData, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/repeater_proto.OwlRepeaterService/ReceiveTimeSeriesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OwlRepeaterServiceServer is the server API for OwlRepeaterService service.
type OwlRepeaterServiceServer interface {
	// ReceiveTimeSeriesData 中继器接收数据
	ReceiveTimeSeriesData(context.Context, *TsData) (*emptypb.Empty, error)
}

func RegisterOwlRepeaterServiceServer(s *grpc.Server, srv OwlRepeaterServiceServer) {
	s.RegisterService(&_OwlRepeaterService_serviceDesc, srv)
}

func _OwlRepeaterService_ReceiveTimeSeriesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TsData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlRepeaterServiceServer).ReceiveTimeSeriesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repeater_proto.OwlRepeaterService/ReceiveTimeSeriesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlRepeaterServiceServer).ReceiveTimeSeriesData(ctx, req.(*TsData))
	}
	return interceptor(ctx, in, info, handler)
}

var _OwlRepeaterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "repeater_proto.OwlRepeaterService",
	HandlerType: (*OwlRepeaterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveTimeSeriesData",
			Handler:    _OwlRepeaterService_ReceiveTimeSeriesData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/repeater.proto",
}
