// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/proto/common.proto

package commonpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HostIdReq struct {
	HostId               string   `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostIdReq) Reset()         { *m = HostIdReq{} }
func (m *HostIdReq) String() string { return proto.CompactTextString(m) }
func (*HostIdReq) ProtoMessage()    {}
func (*HostIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{0}
}

func (m *HostIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostIdReq.Unmarshal(m, b)
}
func (m *HostIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostIdReq.Marshal(b, m, deterministic)
}
func (m *HostIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostIdReq.Merge(m, src)
}
func (m *HostIdReq) XXX_Size() int {
	return xxx_messageInfo_HostIdReq.Size(m)
}
func (m *HostIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HostIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_HostIdReq proto.InternalMessageInfo

func (m *HostIdReq) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

type TsData struct {
	Metric               string            `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	DataType             string            `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Value                float64           `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp            int64             `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Cycle                int32             `protobuf:"varint,5,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TsData) Reset()         { *m = TsData{} }
func (m *TsData) String() string { return proto.CompactTextString(m) }
func (*TsData) ProtoMessage()    {}
func (*TsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{1}
}

func (m *TsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TsData.Unmarshal(m, b)
}
func (m *TsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TsData.Marshal(b, m, deterministic)
}
func (m *TsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TsData.Merge(m, src)
}
func (m *TsData) XXX_Size() int {
	return xxx_messageInfo_TsData.Size(m)
}
func (m *TsData) XXX_DiscardUnknown() {
	xxx_messageInfo_TsData.DiscardUnknown(m)
}

var xxx_messageInfo_TsData proto.InternalMessageInfo

func (m *TsData) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *TsData) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *TsData) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TsData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TsData) GetCycle() int32 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

func (m *TsData) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type TsDataArray struct {
	Data                 []*TsData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TsDataArray) Reset()         { *m = TsDataArray{} }
func (m *TsDataArray) String() string { return proto.CompactTextString(m) }
func (*TsDataArray) ProtoMessage()    {}
func (*TsDataArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{2}
}

func (m *TsDataArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TsDataArray.Unmarshal(m, b)
}
func (m *TsDataArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TsDataArray.Marshal(b, m, deterministic)
}
func (m *TsDataArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TsDataArray.Merge(m, src)
}
func (m *TsDataArray) XXX_Size() int {
	return xxx_messageInfo_TsDataArray.Size(m)
}
func (m *TsDataArray) XXX_DiscardUnknown() {
	xxx_messageInfo_TsDataArray.DiscardUnknown(m)
}

var xxx_messageInfo_TsDataArray proto.InternalMessageInfo

func (m *TsDataArray) GetData() []*TsData {
	if m != nil {
		return m.Data
	}
	return nil
}

type Metric struct {
	HostId               string            `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Metric               string            `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	DataType             string            `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Cycle                int32             `protobuf:"varint,4,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{3}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *Metric) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *Metric) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Metric) GetCycle() int32 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

func (m *Metric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Metrics struct {
	Metrics              []*Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{4}
}

func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type AgentInfo struct {
	HostId               string            `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Ip                   string            `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname             string            `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion         string            `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	AgentOs              string            `protobuf:"bytes,5,opt,name=agent_os,json=agentOs,proto3" json:"agent_os,omitempty"`
	AgentArch            string            `protobuf:"bytes,6,opt,name=agent_arch,json=agentArch,proto3" json:"agent_arch,omitempty"`
	Uptime               float64           `protobuf:"fixed64,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	IdlePct              float64           `protobuf:"fixed64,8,opt,name=idle_pct,json=idlePct,proto3" json:"idle_pct,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AgentInfo) Reset()         { *m = AgentInfo{} }
func (m *AgentInfo) String() string { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()    {}
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{5}
}

func (m *AgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInfo.Unmarshal(m, b)
}
func (m *AgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInfo.Marshal(b, m, deterministic)
}
func (m *AgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInfo.Merge(m, src)
}
func (m *AgentInfo) XXX_Size() int {
	return xxx_messageInfo_AgentInfo.Size(m)
}
func (m *AgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInfo proto.InternalMessageInfo

func (m *AgentInfo) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *AgentInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AgentInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AgentInfo) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *AgentInfo) GetAgentOs() string {
	if m != nil {
		return m.AgentOs
	}
	return ""
}

func (m *AgentInfo) GetAgentArch() string {
	if m != nil {
		return m.AgentArch
	}
	return ""
}

func (m *AgentInfo) GetUptime() float64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *AgentInfo) GetIdlePct() float64 {
	if m != nil {
		return m.IdlePct
	}
	return 0
}

func (m *AgentInfo) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Plugins struct {
	Plugins              []*Plugin `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Plugins) Reset()         { *m = Plugins{} }
func (m *Plugins) String() string { return proto.CompactTextString(m) }
func (*Plugins) ProtoMessage()    {}
func (*Plugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{6}
}

func (m *Plugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugins.Unmarshal(m, b)
}
func (m *Plugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugins.Marshal(b, m, deterministic)
}
func (m *Plugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugins.Merge(m, src)
}
func (m *Plugins) XXX_Size() int {
	return xxx_messageInfo_Plugins.Size(m)
}
func (m *Plugins) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugins.DiscardUnknown(m)
}

var xxx_messageInfo_Plugins proto.InternalMessageInfo

func (m *Plugins) GetPlugins() []*Plugin {
	if m != nil {
		return m.Plugins
	}
	return nil
}

type Plugin struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Checksum             string   `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Args                 string   `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	Interval             int32    `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout              int32    `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Comment              string   `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plugin) Reset()         { *m = Plugin{} }
func (m *Plugin) String() string { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()    {}
func (*Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ad6aa6445208da, []int{7}
}

func (m *Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin.Unmarshal(m, b)
}
func (m *Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin.Marshal(b, m, deterministic)
}
func (m *Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin.Merge(m, src)
}
func (m *Plugin) XXX_Size() int {
	return xxx_messageInfo_Plugin.Size(m)
}
func (m *Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin proto.InternalMessageInfo

func (m *Plugin) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Plugin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plugin) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Plugin) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *Plugin) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *Plugin) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Plugin) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Plugin) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func init() {
	proto.RegisterType((*HostIdReq)(nil), "owl.common.HostIdReq")
	proto.RegisterType((*TsData)(nil), "owl.common.TsData")
	proto.RegisterMapType((map[string]string)(nil), "owl.common.TsData.TagsEntry")
	proto.RegisterType((*TsDataArray)(nil), "owl.common.TsDataArray")
	proto.RegisterType((*Metric)(nil), "owl.common.Metric")
	proto.RegisterMapType((map[string]string)(nil), "owl.common.Metric.TagsEntry")
	proto.RegisterType((*Metrics)(nil), "owl.common.Metrics")
	proto.RegisterType((*AgentInfo)(nil), "owl.common.AgentInfo")
	proto.RegisterMapType((map[string]string)(nil), "owl.common.AgentInfo.MetadataEntry")
	proto.RegisterType((*Plugins)(nil), "owl.common.Plugins")
	proto.RegisterType((*Plugin)(nil), "owl.common.Plugin")
}

func init() { proto.RegisterFile("common/proto/common.proto", fileDescriptor_f2ad6aa6445208da) }

var fileDescriptor_f2ad6aa6445208da = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xd1, 0x8a, 0xd3, 0x4e,
	0x14, 0xc6, 0x49, 0xda, 0x24, 0xcd, 0xd9, 0xff, 0xfe, 0x59, 0x06, 0xd1, 0xec, 0xba, 0x42, 0xc9,
	0x8a, 0xf4, 0x42, 0xba, 0xa2, 0xc8, 0x8a, 0x5e, 0xc8, 0x8a, 0x82, 0x7b, 0x21, 0x2e, 0x43, 0xf1,
	0xc2, 0x9b, 0x32, 0xa6, 0x63, 0x13, 0x36, 0xc9, 0xc4, 0xcc, 0xb4, 0x4b, 0xde, 0xce, 0xb7, 0xf0,
	0xd6, 0x67, 0xf0, 0x09, 0x64, 0xce, 0x69, 0xd2, 0x4a, 0xdb, 0x0b, 0xc1, 0xab, 0xce, 0x77, 0xce,
	0x97, 0x99, 0x33, 0xbf, 0x6f, 0x28, 0x1c, 0x27, 0xaa, 0x28, 0x54, 0x79, 0x5e, 0xd5, 0xca, 0xa8,
	0x73, 0x12, 0x63, 0x14, 0x0c, 0xd4, 0x6d, 0x3e, 0xa6, 0x4a, 0xfc, 0x10, 0xc2, 0xf7, 0x4a, 0x9b,
	0xab, 0x19, 0x97, 0xdf, 0xd8, 0x3d, 0x08, 0x52, 0xa5, 0xcd, 0x34, 0x9b, 0x45, 0xce, 0xd0, 0x19,
	0x85, 0xdc, 0x4f, 0xb1, 0x17, 0xff, 0x72, 0xc0, 0x9f, 0xe8, 0xb7, 0xc2, 0x08, 0x76, 0x17, 0xfc,
	0x42, 0x9a, 0x3a, 0x4b, 0x5a, 0x0b, 0x29, 0x76, 0x1f, 0xc2, 0x99, 0x30, 0x62, 0x6a, 0x9a, 0x4a,
	0x46, 0x2e, 0xb6, 0x06, 0xb6, 0x30, 0x69, 0x2a, 0xc9, 0xee, 0x80, 0xb7, 0x14, 0xf9, 0x42, 0x46,
	0xbd, 0xa1, 0x33, 0x72, 0x38, 0x09, 0x76, 0x0a, 0xa1, 0xc9, 0x0a, 0xa9, 0x8d, 0x28, 0xaa, 0xa8,
	0x3f, 0x74, 0x46, 0x3d, 0xbe, 0x2e, 0xd8, 0x6f, 0x92, 0x26, 0xc9, 0x65, 0xe4, 0x0d, 0x9d, 0x91,
	0xc7, 0x49, 0xb0, 0x27, 0xd0, 0x37, 0x62, 0xae, 0x23, 0x7f, 0xd8, 0x1b, 0x1d, 0x3c, 0x3d, 0x1d,
	0xaf, 0xaf, 0x32, 0xa6, 0x01, 0xc7, 0x13, 0x31, 0xd7, 0xef, 0x4a, 0x53, 0x37, 0x1c, 0x9d, 0x27,
	0x17, 0x10, 0x76, 0x25, 0x76, 0x04, 0xbd, 0x1b, 0xd9, 0xac, 0x46, 0xb7, 0xcb, 0xf5, 0x68, 0x34,
	0x33, 0x89, 0x97, 0xee, 0x0b, 0x27, 0x7e, 0x0e, 0x07, 0xb4, 0xe5, 0x65, 0x5d, 0x8b, 0x86, 0x3d,
	0x82, 0xbe, 0xbd, 0x4f, 0xe4, 0xe0, 0xc9, 0x6c, 0xfb, 0x64, 0x8e, 0xfd, 0xf8, 0x87, 0x03, 0xfe,
	0x07, 0x62, 0xb2, 0x8f, 0xe7, 0x06, 0x44, 0x77, 0x3f, 0xc4, 0xde, 0x36, 0x44, 0x02, 0xd2, 0xdf,
	0x05, 0xc4, 0xdb, 0x06, 0x42, 0x53, 0xfc, 0x3b, 0x20, 0x17, 0x10, 0xd0, 0x96, 0x9a, 0x3d, 0x86,
	0x80, 0x46, 0xd6, 0xbb, 0x78, 0x90, 0x8b, 0xb7, 0x96, 0xf8, 0xa7, 0x0b, 0xe1, 0xe5, 0x5c, 0x96,
	0xe6, 0xaa, 0xfc, 0xaa, 0xf6, 0x53, 0xf9, 0x1f, 0xdc, 0xac, 0x5a, 0x1d, 0xeb, 0x66, 0x15, 0x3b,
	0x81, 0x81, 0xed, 0x94, 0xa2, 0xe8, 0x60, 0xb4, 0x9a, 0x9d, 0xc1, 0xa1, 0xb0, 0x3b, 0x4e, 0x97,
	0xb2, 0xd6, 0x99, 0x2a, 0x11, 0x4a, 0xc8, 0xff, 0xc3, 0xe2, 0x27, 0xaa, 0xb1, 0x63, 0x18, 0x90,
	0x49, 0x69, 0x7c, 0x45, 0x21, 0x0f, 0x50, 0x7f, 0xd4, 0xec, 0x01, 0x00, 0xb5, 0x44, 0x9d, 0xa4,
	0x91, 0x8f, 0xcd, 0x10, 0x2b, 0x97, 0x75, 0x92, 0xda, 0x80, 0x16, 0x95, 0x7d, 0x8b, 0x51, 0x80,
	0x2f, 0x76, 0xa5, 0xec, 0x8e, 0xd9, 0x2c, 0x97, 0xd3, 0x2a, 0x31, 0xd1, 0x00, 0x3b, 0x81, 0xd5,
	0xd7, 0x89, 0x61, 0xaf, 0x61, 0x50, 0x48, 0x23, 0xf0, 0x8d, 0x84, 0xc8, 0xe4, 0x6c, 0x93, 0x49,
	0x77, 0x7f, 0x4b, 0x07, 0x5d, 0x94, 0x49, 0xf7, 0xd1, 0xc9, 0x2b, 0x38, 0xfc, 0xa3, 0xf5, 0xb7,
	0xd9, 0x5c, 0xe7, 0x8b, 0x79, 0x56, 0x62, 0x36, 0x15, 0x2d, 0x77, 0x65, 0x43, 0x2e, 0xde, 0x5a,
	0xe2, 0xef, 0x0e, 0xf8, 0x54, 0x43, 0xfe, 0x94, 0xc9, 0x21, 0x77, 0xb3, 0x19, 0x63, 0xd0, 0x47,
	0xf6, 0x74, 0x18, 0xae, 0x6d, 0xad, 0x12, 0x26, 0x5d, 0xe5, 0x81, 0x6b, 0x9b, 0x53, 0x92, 0xca,
	0xe4, 0x46, 0x2f, 0x8a, 0x55, 0x0c, 0x9d, 0xb6, 0x7e, 0x51, 0xcf, 0x5b, 0xfc, 0xb8, 0xb6, 0xfe,
	0xac, 0x34, 0xb2, 0x5e, 0x8a, 0x1c, 0xc9, 0x7b, 0xbc, 0xd3, 0x2c, 0x82, 0xc0, 0x82, 0x56, 0x0b,
	0x83, 0xe4, 0x3d, 0xde, 0x4a, 0xdb, 0xb1, 0x57, 0x90, 0x25, 0x91, 0x0f, 0x79, 0x2b, 0xdf, 0xb0,
	0xcf, 0x47, 0xea, 0x36, 0x3f, 0xdf, 0xfc, 0xc3, 0xfb, 0xe2, 0xe3, 0xcf, 0xb3, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x3a, 0xa6, 0x8a, 0x70, 0x07, 0x05, 0x00, 0x00,
}
