package main

const (
	HOSTCONFIG byte = iota //主机配置信息
	HOSTCONFIGRESP
	CLIENTVERSION //客户端版本号
	CLIENTVERSIONRESP
	SERIESDATA //监控数据

	GETDEVICES
	GETDEVICESRESP
	GETPORTS
	GETPORTSRESP
	UPDATEDEVICES //代理更新网络设备信息
	UPDATEPORTS   //代理更新主机端口状态

	PORTDISCOVERYR  //端口自动发现数据
	ASSESTDISCOVERY //资产自动发现

	HOSTHB
	GUARDHB
)

var PROTOCOLTYPE = []string{
	"HOSTCONFIG",
	"HOSTCONFIGRESP",
	"CLIENTVERSION",
	"CLIENTVERSIONRESP",
	"SERIESDATA",
	"GETDEVICES",
	"GETDEVICESRESP",
	"GETPORTS",
	"GETPORTSRESP",
	"UPDATEDEVICES",
	"UPDATEPORTS",
	"PORTDISCOVERYR",
	"ASSESTDISCOVERY",
	"HOSTHB",
	"GUARDHB",
}
